language: node_js

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

install:
  - npm install
  - ./node_modules/.bin/bower install

script:
  - ./node_modules/.bin/gulp --production

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./after_success.sh
