language: node_js

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    secure: "scuUw9QoExNIzniMi6R36LqfwDjmKp6BKrmu/U5DFbic+QXojRrrg5gC8bCailiRpmmIrJYsUpOvVLQANnXeAvk52b6V3TDrQLQ+cYhr13pLYoDb17gkQlgxNeM1Bhxm0MFE+s/j5mcp19AzzhGmALkDx9o3eLTZYLDibKdcz0o="

install:
  - npm install

script:
  - ./node_modules/.bin/gulp

after_success:
  - git clone https://$GIT_NAME:$GH_TOKEN@github.com/skunenieki/skunenieki.github.io.git
  - cp -r public/* skunenieki.github.io/
  - git status
  - git add --all .
  - git config --global user.name $GIT_NAME
  - git config --global user.email $GIT_EMAIL
  - git config --global push.default simple
  - export C=`git rev-parse --verify HEAD`
  - git commit --allow-empty -m "Updating to $TRAVIS_REPO_SLUG@#$C"
  - git push --quiet origin master
